### ISSUE TITLE
"Method Illuminate\\Config\\Repository::restore does not exist."

### ISSUE THREAD

**Issue by joserick** [illuminatech/nova-config#4]
### What steps will reproduce the problem?
- Package installation
- Configuration

### What is the expected result?
To load the component

### What do you get instead?
Error: "Method Illuminate\\Config\\Repository::restore does not exist."

### Additional info

The component controller constructor that executes the "$container->get('config')" method returns an "Illuminate\Config\Repository" instance instead of an "Illuminatech\Config\PersistentRepository"

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.0.2
| Laravel Framework Version | 9.46.0
| Laravel Nova Version      | 3.32.0
| PHP version               |  8.1
| Operating system          |  Ubuntu 22.04.1 LTS

**Comment by klimov-paul** [comment]
https://github.com/illuminatech/nova-config/blame/1.0.2/README.md#L43-L44

> This extension relies on [illuminatech/config](https://github.com/illuminatech/config) package for the actual configuration management.
Make sure you are familiar with [illuminatech/config](https://github.com/illuminatech/config) package before attempting to use this one.
