### ISSUE TITLE
e.fill is not a function

### ISSUE THREAD

**Issue by szwss** [illuminatech/nova-config#7]
### What steps will reproduce the problem?
The first time I click the Save button, the data is saved normally, 
but when I click the Save button for the second time, an error will be reported
```
TypeError: e.fill is not a function
    at nova-config:1:2195
    at nova-config:1:106892
    at Gr (nova-config:1:96765)
    at nova-config:1:106697
    at Function.Vu (nova-config:1:119149)
    at nova-config:1:2167
    at vr.tap (nova-config:1:133513)
    at a.submitConfigForm (nova-config:1:2136)
    at It (vendor.js?id=ddcebc8a821be6b5c7b8:1:1153148)
    at HTMLFormElement.n (vendor.js?id=ddcebc8a821be6b5c7b8:1:1154882)
```

### What is the expected result?
Submit data as normal

### What do you get instead?
![image](https://github.com/user-attachments/assets/6bc890d0-e6c5-4759-af26-1f1cead367f9)

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.0.2
| Laravel Framework Version | 8.83.27
| Laravel Nova Version      | 3.32.0
| PHP version               |  v7.4.33

| Operating system          | untuntu 22.04

**Comment by klimov-paul** [comment]
Laravel Nova version 3.x is no longer supported as well as this package's version 1.x.

Please use the latest version for both packages:

```json
"laravel/nova": "^4.0.0",
"illuminatech/nova-config": "^2.0"
```
